services:
  backend_dev:
    container_name: backend_dev
    build: ./src/
    env_file:
      - ./src/.env
    ports:
      - "8081:8081"
    volumes:
      - .:/src
    depends_on:
      - db_dev
    restart: always
    networks:
      - api-myprimera-app
    
  db_dev:
    image: docker.io/bitnami/postgresql:15
    container_name: db_dev
    ports:
      - 5434:5432
    env_file:
      - ./src/.env
    volumes:
      - .db_dev:/var/postgre2
    networks:
      - api-myprimera-app

networks:
  api-develop-app:
    driver: bridge